/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.telasCadastro;

import javax.swing.JButton;
import javax.swing.JPanel;
import javax.swing.JTextField;
import view.FormModeloCadastros;

/**
 *
 * @author julia
 */
public class TelaCadastroCidade extends javax.swing.JFrame {

   /**
    * Creates new form FormModeloCadastros
    */
   public TelaCadastroCidade() {
      initComponents();
   }

   /**
    * This method is called from within the constructor to initialize the form.
    * WARNING: Do NOT modify this code. The content of this method is always
    * regenerated by the Form Editor.
    */
   @SuppressWarnings("unchecked")
   // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
   private void initComponents() {

      north = new javax.swing.JPanel();
      titulo = new javax.swing.JLabel();
      south = new javax.swing.JPanel();
      novo = new javax.swing.JButton();
      cancelar = new javax.swing.JButton();
      gravar = new javax.swing.JButton();
      buscar = new javax.swing.JButton();
      sair = new javax.swing.JButton();
      center = new javax.swing.JPanel();
      descricao = new javax.swing.JLabel();
      textoDescricao = new javax.swing.JTextField();

      setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
      setTitle("Formulário de Cadastro");
      setResizable(false);

      north.setBackground(new java.awt.Color(255, 204, 0));
      north.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
      north.setPreferredSize(new java.awt.Dimension(700, 75));

      titulo.setFont(new java.awt.Font("Leelawadee", 0, 36)); // NOI18N
      titulo.setForeground(new java.awt.Color(0, 0, 0));
      titulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
      titulo.setText("CIDADE");

      javax.swing.GroupLayout northLayout = new javax.swing.GroupLayout(north);
      north.setLayout(northLayout);
      northLayout.setHorizontalGroup(
         northLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(northLayout.createSequentialGroup()
            .addContainerGap()
            .addComponent(titulo, javax.swing.GroupLayout.DEFAULT_SIZE, 684, Short.MAX_VALUE)
            .addContainerGap())
      );
      northLayout.setVerticalGroup(
         northLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(northLayout.createSequentialGroup()
            .addContainerGap()
            .addComponent(titulo, javax.swing.GroupLayout.DEFAULT_SIZE, 59, Short.MAX_VALUE)
            .addContainerGap())
      );

      getContentPane().add(north, java.awt.BorderLayout.NORTH);

      south.setPreferredSize(new java.awt.Dimension(700, 50));

      novo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/novo.png"))); // NOI18N
      novo.setText("Novo");
      novo.setPreferredSize(new java.awt.Dimension(120, 30));
      south.add(novo);

      cancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/cancelar.png"))); // NOI18N
      cancelar.setText("Cancelar");
      cancelar.setEnabled(false);
      cancelar.setPreferredSize(new java.awt.Dimension(120, 30));
      south.add(cancelar);

      gravar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/gravar2.png"))); // NOI18N
      gravar.setText("Gravar");
      gravar.setEnabled(false);
      gravar.setPreferredSize(new java.awt.Dimension(120, 30));
      south.add(gravar);

      buscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/buscar.png"))); // NOI18N
      buscar.setText("Buscar");
      buscar.setPreferredSize(new java.awt.Dimension(120, 30));
      south.add(buscar);

      sair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/sair.png"))); // NOI18N
      sair.setText("Sair");
      sair.setPreferredSize(new java.awt.Dimension(120, 30));
      south.add(sair);

      getContentPane().add(south, java.awt.BorderLayout.SOUTH);

      descricao.setText("Descrição:");

      javax.swing.GroupLayout centerLayout = new javax.swing.GroupLayout(center);
      center.setLayout(centerLayout);
      centerLayout.setHorizontalGroup(
         centerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(centerLayout.createSequentialGroup()
            .addContainerGap()
            .addComponent(descricao)
            .addGap(18, 18, 18)
            .addComponent(textoDescricao, javax.swing.GroupLayout.DEFAULT_SIZE, 616, Short.MAX_VALUE)
            .addContainerGap())
      );
      centerLayout.setVerticalGroup(
         centerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(centerLayout.createSequentialGroup()
            .addGap(71, 71, 71)
            .addGroup(centerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
               .addComponent(descricao)
               .addComponent(textoDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addContainerGap(63, Short.MAX_VALUE))
      );

      getContentPane().add(center, java.awt.BorderLayout.CENTER);

      pack();
      setLocationRelativeTo(null);
   }// </editor-fold>//GEN-END:initComponents

   /**
    * @param args the command line arguments
    */
   public static void main(String args[]) {
      /* Set the Nimbus look and feel */
      //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
      /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
       */
      try {
         for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
            if ("Nimbus".equals(info.getName())) {
               javax.swing.UIManager.setLookAndFeel(info.getClassName());
               break;
            }
         }
      } catch (ClassNotFoundException ex) {
         java.util.logging.Logger.getLogger(FormModeloCadastros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
      } catch (InstantiationException ex) {
         java.util.logging.Logger.getLogger(FormModeloCadastros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
      } catch (IllegalAccessException ex) {
         java.util.logging.Logger.getLogger(FormModeloCadastros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
      } catch (javax.swing.UnsupportedLookAndFeelException ex) {
         java.util.logging.Logger.getLogger(FormModeloCadastros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
      }
      //</editor-fold>

      /* Create and display the form */
      java.awt.EventQueue.invokeLater(new Runnable() {
         public void run() {
            new FormModeloCadastros().setVisible(true);
         }
      });
   }

   // Variables declaration - do not modify//GEN-BEGIN:variables
   private javax.swing.JButton buscar;
   private javax.swing.JButton cancelar;
   private javax.swing.JPanel center;
   private javax.swing.JLabel descricao;
   private javax.swing.JButton gravar;
   private javax.swing.JPanel north;
   private javax.swing.JButton novo;
   private javax.swing.JButton sair;
   private javax.swing.JPanel south;
   private javax.swing.JTextField textoDescricao;
   private javax.swing.JLabel titulo;
   // End of variables declaration//GEN-END:variables

   //botões
   public JButton getBuscar() {
      return buscar;
   }

   public JButton getCancelar() {
      return cancelar;
   }

   public JButton getGravar() {
      return gravar;
   }

   public JButton getNovo() {
      return novo;
   }

   public JButton getSair() {
      return sair;
   }

   //dados
   public JPanel getCenter() {
      return center;
   }

   public JTextField getTextoDescricao() {
      return textoDescricao;
   }
   
}
